.TH RMTREE 1 "September 21, 2013" "Jean-Marc Bourguet" "Jean-Marc Bourguet's Utilities"

.SH NAME
rmtree \- remove directories and their content

.SH SYNOPSIS
.B rmtree
[\fIOPTION\fR]... \fIDIR\fR...

.SH DESCRIPTION
.B rmtree
removes each specified directory and their content.  There are two main
differences with
.B rm -fr
:
.IP \(bu
.B rmtree
is able to add  access right on a directory to do its job; 
.IP \(bu
by default
.B rmtree 
won't remove the content of a directory on which write access have been
removed.

.SH OPTIONS

.TP
\fB\-h\fR
built in help.

.TP
\fB\-v\fR
verbose mode, says what is done.

.TP
\fB\-n\f
dry run, don't do anything.

.TP
\fB\-c\fR
remove only the content of the specified directories but not the
directories themselves.

.TP
\fB\-F\fR
remove write protected files and directories.  Change access rights of
directories in order to remove their content.

.TP
\fB\-M\fR
remove in different file systems.

.TP
\fB\-R\fR
force recursion in directories which won't be removed.  Normally 
.B rmtree
won't recurse in directories when it is know that they won't be removed
(for instance write protected without \-F, with another owner without \-O).

.TP
\fB\-O\fR
remove also only files and directories which aren't owned by the current
user.

.SH EXIT STATUS

.TP
0
all requested files and directories have been removed
.TP
1
some files and directories but not all have been removed
.TP
2
nothing has been removed

.\" .SH NOTES

.\" .SH BUGS

.SH EXAMPLES

.B rmtree foo
.P
Remove the directory foo and its content.

.B rmtree -F foo
.P
Remove the directory foo and its content, even the write protected part,
even if it has to change access rights to achieve its result.

.B rmtree -c .
.P
Remove the content of the current directory, even the hidden files.

.B rmtree -FROM foo
.P
Do a best effort to remove foo.

.SH SEE ALSO

rm(1), rmdir(1)
